services:
  - type: web
    name: eco-city-rubtsovsk
    runtime: python                     # обязательно runtime вместо env
    pythonVersion: 3.10.0                # фиксируем нужную версию
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: eco-city-db
    databaseName: eco_city
    user: eco_city_user
    plan: free
    region: oregon                        # укажите тот же регион, что у веб-сервиса
    ipAllowList: []                        # доступ только из внутренней сети
