services:
  - type: web
    name: eco-city-rubtsovsk
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10.0                 # явно указываем версию Python
    envVars:
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: eco-city-db
    databaseName: eco_city
    user: eco_city_user
    plan: free
    region: oregon                          # укажите тот же регион, что и веб-сервис
    ipAllowList: []                          # разрешить подключения только из внутренней сети