services:
  - type: web
    name: eco-city
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y gcc libpq-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app